// เรียกบล็อกทุกตัว เพื่อให้คอมไพล์ตรวจชนิดข้อมูลครบ
KrathokKidsBit.oledInit(OLED_Address.Addr_0x3C, true)
KrathokKidsBit.oledInit(OLED_Address.Addr_0x3C)
KrathokKidsBit.oledClear()
KrathokKidsBit.oledShowLine("KrathokKidsBit", 1)
KrathokKidsBit.oledShowLine(123, 2)
KrathokKidsBit.oledShowLine("Distance = " + KrathokKidsBit.kidsDistance(), 3)
KrathokKidsBit.oledShowString("Hi", 0, 20, 2, OLED_Color.White)
KrathokKidsBit.oledShowString(42, 60, 20, 1, OLED_Color.Inverse)
KrathokKidsBit.oledShowBig("GO!", 4)
KrathokKidsBit.oledDrawPixel(1, 1, OLED_Color.White)
KrathokKidsBit.oledDrawLine(0, 63, 127, 40, OLED_Color.White)
KrathokKidsBit.oledDrawRect(60, 20, 30, 20, OLED_Fill.Outline, OLED_Color.White)
KrathokKidsBit.oledDrawCircle(110, 40, 10, OLED_Fill.Filled, OLED_Color.Inverse)
KrathokKidsBit.oledProgressBar(0, 54, 100, 10, 70)
KrathokKidsBit.oledSettings(false, 200)
KrathokKidsBit.oledSetAutoUpdate(false)
KrathokKidsBit.oledRefresh()
KrathokKidsBit.oledShowSensor(OLED_SensorView.Bars)
KrathokKidsBit.oledShowSensor(OLED_SensorView.Calibration)

KrathokKidsBit.waitForButton(Kids_Button.A)
KrathokKidsBit.waitForButton(Kids_Button.B, IconNames.Yes, IconNames.Heart)
KrathokKidsBit.robotMove(Kids_Move.Forward, 50)
KrathokKidsBit.robotMove(Kids_Move.SpinLeft, 60, 0.5)
KrathokKidsBit.robotStop()
KrathokKidsBit.robotWheels(30, -30)
KrathokKidsBit.robotSpinDegrees(Kids_LeftRight.Right, 90, 60)
KrathokKidsBit.robotStraightFor(Kids_Direction.Forward, 50, 1)

KrathokKidsBit.lineCalibrate(Kids_CalMode.Sweep)
KrathokKidsBit.lineCalibrate(Kids_CalMode.Points)
KrathokKidsBit.setSensorCal([929, 1667, 1514, 1362, 1273, 969, 595, 558], [3724, 3833, 3829, 3830, 3814, 3782, 2312, 2450])
KrathokKidsBit.lineTuning(Kids_Band.All, 0.05, 0.1)
KrathokKidsBit.lineTuning(Kids_Band.Fast, 0.08, 0.2)
KrathokKidsBit.lineReading(50, 120)
KrathokKidsBit.lineToJunction(Kids_Junction.Center, 2, 80)
KrathokKidsBit.lineToJunction(Kids_Junction.Left, 1, 60, Kids_Then.TurnLeft, 50)
KrathokKidsBit.lineFollowFor(1, 40)
KrathokKidsBit.lineTurn(Kids_LeftRight.Left, 50)
KrathokKidsBit.lineAutoTune(40, 2)

if (KrathokKidsBit.kidsObstacle(15)) KrathokKidsBit.kidsServo(Kids_Servo.S0, KrathokKidsBit.kidsHeading())
KrathokKidsBit.kidsResetHeading()
KrathokKidsBit.oledShowLine(KrathokKidsBit.kidsSensor(Kids_Sensor.ADC3), 8)
KrathokKidsBit.armSetup(Kids_Servo.S0, 175, 5, Kids_Servo.S1, 90, 20)
KrathokKidsBit.armSetup(Kids_Servo.S2, 170, 10, Kids_Servo.S3, 80, 15, 600)
KrathokKidsBit.armDo(Kids_ArmAction.GripAndLift)
KrathokKidsBit.armDo(Kids_ArmAction.PlaceAndRelease)
KrathokKidsBit.lineFollowForever(40)
KrathokKidsBit.haltAll()
KrathokKidsBit.lineToObstacle(15, 40)
KrathokKidsBit.motorRun(Kids_Motor.M1, Kids_MotorDir.Forward, 50)
KrathokKidsBit.motorRun(Kids_Motor.M4, Kids_MotorDir.Backward, 80, 1.5)
KrathokKidsBit.motorOff(Kids_Motor.M1)
