KrathokKidsBit.motorWrite(Motor_Write.Motor_1, 100)
basic.pause(500)
KrathokKidsBit.motorWrite(Motor_Write.Motor_2, -100)
basic.pause(500)
KrathokKidsBit.motorStop()
basic.pause(500)
KrathokKidsBit.Turn(_Turn.Left, 100)
basic.pause(500)
KrathokKidsBit.Spin(_Spin.Right, 100)
basic.pause(500)
KrathokKidsBit.servoWrite(Servo_Write.S0, 180)
basic.pause(500)
KrathokKidsBit.servoWrite(Servo_Write.S0, 90)
basic.forever(function () {
    basic.showNumber(KrathokKidsBit.ADCRead(ADC_Read.ADC0))
})
KrathokKidsBit.oledInit(OLED_Address.Addr_0x3C)
KrathokKidsBit.oledClear()
KrathokKidsBit.oledShowLine("KrathokKidsBit", 0)
KrathokKidsBit.oledShowNumberLine(123, 1)
KrathokKidsBit.oledShowString("Hi", 0, 20, 2, OLED_Color.White)
KrathokKidsBit.oledDrawRect(60, 20, 30, 20, OLED_Fill.Outline, OLED_Color.White)
KrathokKidsBit.oledDrawCircle(110, 40, 10, OLED_Fill.Filled, OLED_Color.Inverse)
KrathokKidsBit.oledDrawLine(0, 63, 127, 40, OLED_Color.White)
KrathokKidsBit.oledProgressBar(0, 54, 100, 10, 70)
KrathokKidsBit.oledSetAutoUpdate(false)
KrathokKidsBit.oledDrawPixel(1, 1, OLED_Color.White)
KrathokKidsBit.oledRefresh()
KrathokKidsBit.oledInvert(false)
KrathokKidsBit.oledBrightness(128)
KrathokKidsBit.oledDisplay(OLED_OnOff.On)
KrathokKidsBit.robotMove(Kids_Move.Forward, 50)
KrathokKidsBit.robotMoveFor(Kids_Move.SpinLeft, 60, 0.5)
KrathokKidsBit.robotStop()
KrathokKidsBit.robotWheels(30, -30)
KrathokKidsBit.robotSpinDegrees(Kids_LeftRight.Right, 90, 60)
KrathokKidsBit.robotStraightFor(Kids_Direction.Forward, 50, 1)
KrathokKidsBit.lineSetupStandard()
KrathokKidsBit.lineCalibrate()
KrathokKidsBit.lineFollow(40)
KrathokKidsBit.lineToJunction(Kids_Junction.Center, 2, 40)
KrathokKidsBit.lineFollowFor(1, 40)
KrathokKidsBit.lineTurn(Kids_LeftRight.Left, 50)
KrathokKidsBit.lineTuning(0.05, 0.1)
KrathokKidsBit.oledShowValue("Distance", KrathokKidsBit.kidsDistance(), 3)
KrathokKidsBit.oledShowBig("GO!", 4)
if (KrathokKidsBit.kidsObstacle(15)) KrathokKidsBit.kidsServo(Kids_Servo.S0, KrathokKidsBit.kidsHeading())
KrathokKidsBit.kidsResetHeading()
KrathokKidsBit.oledShowNumberLine(KrathokKidsBit.kidsSensor(Kids_Sensor.ADC3), 8)
KrathokKidsBit.TurnLINEPro(Turn_Line.Left, 80, 30, 30)
KrathokKidsBit.TurnLINEPro(Turn_Line.Right, 70, 25, 0)
