PTKidsBITVX.motorWrite(Motor_Write.Motor_1, 100)
basic.pause(500)
PTKidsBITVX.motorWrite(Motor_Write.Motor_2, -100)
basic.pause(500)
PTKidsBITVX.motorStop()
basic.pause(500)
PTKidsBITVX.Turn(_Turn.Left, 100)
basic.pause(500)
PTKidsBITVX.Spin(_Spin.Right, 100)
basic.pause(500)
PTKidsBITVX.servoWrite(Servo_Write.S0, 180)
basic.pause(500)
PTKidsBITVX.servoWrite(Servo_Write.S0, 90)
basic.forever(function () {
    basic.showNumber(PTKidsBITVX.ADCRead(ADC_Read.ADC0))
})
PTKidsBITVX.oledInit(OLED_Address.Addr_0x3C)
PTKidsBITVX.oledClear()
PTKidsBITVX.oledShowLine("PTKidsBIT VX", 0)
PTKidsBITVX.oledShowNumberLine(123, 1)
PTKidsBITVX.oledShowString("Hi", 0, 20, 2, OLED_Color.White)
PTKidsBITVX.oledDrawRect(60, 20, 30, 20, OLED_Fill.Outline, OLED_Color.White)
PTKidsBITVX.oledDrawCircle(110, 40, 10, OLED_Fill.Filled, OLED_Color.Inverse)
PTKidsBITVX.oledDrawLine(0, 63, 127, 40, OLED_Color.White)
PTKidsBITVX.oledProgressBar(0, 54, 100, 10, 70)
PTKidsBITVX.oledSetAutoUpdate(false)
PTKidsBITVX.oledDrawPixel(1, 1, OLED_Color.White)
PTKidsBITVX.oledRefresh()
PTKidsBITVX.oledInvert(false)
PTKidsBITVX.oledBrightness(128)
PTKidsBITVX.oledDisplay(OLED_OnOff.On)
